"""Create applicants table

Revision ID: 0dff4b5ceafa
Revises: bbc404b408fe
Create Date: 2025-09-10 09:35:14.301148

"""
from alembic import op
import sqlalchemy as sa

from app.database.custom_types import ChoiceType
from app.models.applicants import Applicant

# revision identifiers, used by Alembic
revision = '0dff4b5ceafa'
down_revision = 'bbc404b408fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', ChoiceType(choices=Applicant.GENDER_CHOICES), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants')
    # ### end Alembic commands ###
