"""Create Services table

Revision ID: 186d71632e90
Revises: e6641e2dd1f3
Create Date: 2025-09-04 11:48:48.350254

"""
from alembic import op
import sqlalchemy as sa

from app.database.custom_types import ChoiceType
from app.models import Service


# revision identifiers, used by Alembic
revision = '186d71632e90'
down_revision = 'e6641e2dd1f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fee_type', ChoiceType(choices=Service.FEE_TYPE_CHOICES), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('urgency_id', sa.Integer(), nullable=True),
    sa.Column('visa_duration_id', sa.Integer(), nullable=True),
    sa.Column('visa_type_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name="services_country_id_fkey", ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['urgency_id'], ['urgencies.id'], name="services_urgency_id_fkey", ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visa_duration_id'], ['visa_durations.id'], name="services_visa_duration_fkey", ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], name="services_visa_type_id_fkey", ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_country_id_fkey', table_name='services', type_='foreignkey')
    op.drop_constraint('services_urgency_id_fkey', table_name='services', type_='foreignkey')
    op.drop_constraint('services_visa_duration_fkey', table_name='services', type_='foreignkey')
    op.drop_constraint('services_visa_type_id_fkey', table_name='services', type_='foreignkey')
    op.drop_table('services')
    # ### end Alembic commands ###
