"""Client add col is_active

Revision ID: 2127857ff9f2
Revises: 5964b031d774
Create Date: 2025-08-29 08:54:21.828635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '2127857ff9f2'
down_revision = '5964b031d774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
