"""Creare country_visas table

Revision ID: 336c0f712670
Revises: 5964b031d774
Create Date: 2025-08-27 08:21:16.823803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '336c0f712670'
down_revision = '5964b031d774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_visas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('visa_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_visas')
    # ### end Alembic commands ###
