"""Audit model set model_type nullable True

Revision ID: 4fc52a9ca389
Revises: 527ffbe2d561
Create Date: 2025-08-18 13:00:49.443818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '4fc52a9ca389'
down_revision = '527ffbe2d561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_entries', 'model_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_entries', 'model_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
