"""Add target_id model to LogEntry

Revision ID: 527ffbe2d561
Revises: fe32b17c7e29
Create Date: 2025-08-18 12:59:40.279830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '527ffbe2d561'
down_revision = 'fe32b17c7e29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('target_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entries', 'target_id')
    # ### end Alembic commands ###
