"""Creare visa_urgencies table

Revision ID: 5964b031d774
Revises: c532dd532a8e
Create Date: 2025-08-27 07:50:13.597271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '5964b031d774'
down_revision = 'c532dd532a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_urgencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visa_urgencies')
    # ### end Alembic commands ###
