"""Create password reset confirm table

Revision ID: 5d149ad35a59
Revises: aaac4492587a
Create Date: 2025-08-22 14:19:10.584395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '5d149ad35a59'
down_revision = 'aaac4492587a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_confirm',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_confirm_id'), 'password_reset_confirm', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_confirm_id'), table_name='password_reset_confirm')
    op.drop_table('password_reset_confirm')
    # ### end Alembic commands ###
