"""Create countries table

Revision ID: 6b56bb31cecf
Revises: a8c001c2da33
Create Date: 2025-08-26 08:28:30.088003

"""
import json
from pathlib import Path

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic
revision = '6b56bb31cecf'
down_revision = 'a8c001c2da33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    countries_json_file = Path(__file__).parent / '../../../../fixtures/countries.json'
    # Create countries table
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alpha2', sa.String(), nullable=False),
    sa.Column('alpha3', sa.String(), nullable=False),
    sa.Column('available_for_order', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # insert Countries from fixtures
    with open(countries_json_file, 'r') as f:
        data = json.load(f)

    # create a session
    bind = op.get_bind()
    session = Session(bind=bind)

    try:
        for item in data:
            item.update({"available_for_order": False})
            session.execute(
                sa.text(
                    "INSERT INTO countries (name, alpha2, alpha3, available_for_order) "
                    "VALUES (:name, :alpha2, :alpha3, :available_for_order)"),
                item
            )
        session.commit()
    finally:
        session.close()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
