"""Create order_services table

Revision ID: 7b222dc4c30c
Revises: 9c038e5bcd71
Create Date: 2025-09-17 09:30:32.801533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '7b222dc4c30c'
down_revision = '9c038e5bcd71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_services',
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_service_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='order_service_service_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_service_order_id_fkey", table_name='orders', type_="foreignkey")
    op.drop_constraint("order_service_service_id_fkey", table_name='services', type_="foreignkey")
    op.drop_table('order_services')
    # ### end Alembic commands ###
