"""Create tarif_services table

Revision ID: 839010ba322c
Revises: 186d71632e90
Create Date: 2025-09-04 13:10:54.107600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '839010ba322c'
down_revision = '186d71632e90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_services',
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name="tariff_services_service_id_fkey", ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name="tariff_services_tariff_id_fkey", ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(constraint_name="uq_tariff_service_service_tariff", table_name="tariff_services", columns=['service_id', 'tariff_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tariff_services_service_id_fkey', table_name='tariff_services', type_='foreignkey')
    op.drop_constraint('tariff_services_tariff_id_fkey', table_name='tariff_services', type_='foreignkey')
    op.drop_constraint('uq_tariff_service_service_tariff', table_name='tariff_services', type_='unique')
    op.drop_table('tariff_services')
    # ### end Alembic commands ###
