"""user first, last name

Revision ID: 8393cb0a2e12
Revises: 9b26bc834f51
Create Date: 2025-08-13 15:31:47.892401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '8393cb0a2e12'
down_revision = '9b26bc834f51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
