"""Add role column to users table

Revision ID: 8453a56ca7d1
Revises: e0acab11d70c
Create Date: 2025-08-18 10:38:07.758460

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from app.models.users import User

# revision identifiers, used by Alembic
revision = '8453a56ca7d1'
down_revision = 'e0acab11d70c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(User.ROLE_CHOICES), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
