"""Create country_visas table

Revision ID: 8c8714de2aed
Revises: 2127857ff9f2
Create Date: 2025-08-29 09:26:58.061275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '8c8714de2aed'
down_revision = '2127857ff9f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_visas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('visa_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_visas')
    # ### end Alembic commands ###
