"""Create uniqueConstraint uq_visa_duration_term_entry

Revision ID: 8cf660c9e2bb
Revises: deff74404810
Create Date: 2025-09-02 11:50:00.054875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '8cf660c9e2bb'
down_revision = 'deff74404810'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_visa_duration_term_entry', 'visa_durations', ['term', 'entry'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_visa_duration_term_entry', 'visa_durations', type_='unique')
    # ### end Alembic commands ###
