"""Add email to clients table

Revision ID: 9c038e5bcd71
Revises: 0dff4b5ceafa
Create Date: 2025-09-15 17:25:29.041910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.models import Client


# revision identifiers, used by Alembic
revision = '9c038e5bcd71'
down_revision = '0dff4b5ceafa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(length=100), nullable=True))
    op.alter_column('orders', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # Get the current connection and session
    bind = op.get_bind()
    session = Session(bind=bind)

    # Fetch all clients and associated users
    clients = session.execute(
        sa.select(Client)
    ).scalars().all()

    for client in clients:
        if client.individual:
            client.email = client.individual.email

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
