"""Add created_at and updated_at to client model

Revision ID: a8c001c2da33
Revises: b7a1156558f1
Create Date: 2025-08-22 13:42:49.990004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'a8c001c2da33'
down_revision = 'b7a1156558f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    # ### end Alembic commands ###
