"""Create email confirm table

Revision ID: aaac4492587a
Revises: a8c001c2da33
Create Date: 2025-08-22 14:13:22.255790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'aaac4492587a'
down_revision = 'a8c001c2da33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_confirm',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_confirm_id'), 'email_confirm', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_confirm_id'), table_name='email_confirm')
    op.drop_table('email_confirm')
    # ### end Alembic commands ###
