"""Set user role nullable = False

Revision ID: b97e35bddf3a
Revises: 8453a56ca7d1
Create Date: 2025-08-18 10:39:40.128627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'b97e35bddf3a'
down_revision = '8453a56ca7d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###
