"""Create orders table

Revision ID: bbc404b408fe
Revises: 839010ba322c
Create Date: 2025-09-10 08:48:07.435751

"""
from alembic import op
import sqlalchemy as sa

from app.database.custom_types import ChoiceType
from app.models.order import Order


# revision identifiers, used by Alembic
revision = 'bbc404b408fe'
down_revision = '839010ba322c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
sa.Column('status', ChoiceType(choices=Order.STATUS_CHOICES), server_default='new', nullable=False),
        sa.Column('number', sa.String(), nullable=False),
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('urgency_id', sa.Integer(), nullable=False),
        sa.Column('visa_duration_id', sa.Integer(), nullable=False),
        sa.Column('visa_type_id', sa.Integer(), nullable=False),
        sa.Column('archived_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='orders_client_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='orders_country_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='orders_created_by_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['urgency_id'], ['urgencies.id'], name='orders_urgency_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['visa_duration_id'], ['visa_durations.id'], name='orders_visa_duration_id_fkey'),
        sa.ForeignKeyConstraint(['visa_type_id'], ['visa_types.id'], name='orders_visa_type_id_fkey'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_client_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_country_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_created_by_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_urgency_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_visa_duration_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_visa_type_id_fkey', 'orders', type_='foreignkey')

    op.drop_table('orders')
    # ### end Alembic commands ###
