"""Creare visatypes table

Revision ID: c532dd532a8e
Revises: 6b56bb31cecf
Create Date: 2025-08-27 07:46:14.365671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'c532dd532a8e'
down_revision = '6b56bb31cecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visa_types')
    # ### end Alembic commands ###
