"""Clients table add is_active

Revision ID: cfa6505cae1b
Revises: 336c0f712670
Create Date: 2025-08-28 10:29:17.697737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'cfa6505cae1b'
down_revision = '336c0f712670'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
