"""Create tariffs table

Revision ID: d929fd812882
Revises: 4fc52a9ca389
Create Date: 2025-08-21 09:54:22.753380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'd929fd812882'
down_revision = '4fc52a9ca389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO tariffs (name, is_default) VALUES ('Basic Tariff', TRUE)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariffs')
    # ### end Alembic commands ###
