"""Create visa_durations table

Revision ID: deff74404810
Revises: 8c8714de2aed
Create Date: 2025-09-02 11:28:34.534322

"""
from alembic import op
import sqlalchemy as sa

from app.database.custom_types import ChoiceType
from app.models.visa_durations import VisaDuration


# revision identifiers, used by Alembic
revision = 'deff74404810'
down_revision = '8c8714de2aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_durations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('term', ChoiceType(choices=VisaDuration.TERM_CHOICES), nullable=False),
    sa.Column('entry', ChoiceType(choices=VisaDuration.ENTRY_CHOICES), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visa_durations')
    # ### end Alembic commands ###
