"""Create log_entries table

Revision ID: e0acab11d70c
Revises: 61d55ffb777f
Create Date: 2025-08-18 10:30:21.777483

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from app.models.audit import LogEntry


# revision identifiers, used by Alembic
revision = 'e0acab11d70c'
down_revision = '61d55ffb777f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlalchemy_utils.types.choice.ChoiceType(choices=LogEntry.ACTION_CHOICES), nullable=False),
    sa.Column('model_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entries')
    # ### end Alembic commands ###
