"""Create country_visa_duration

Revision ID: e6641e2dd1f3
Revises: 8cf660c9e2bb
Create Date: 2025-09-02 14:07:24.837163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'e6641e2dd1f3'
down_revision = '8cf660c9e2bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_visa_duration',
    sa.Column('country_visa_id', sa.Integer(), nullable=False),
    sa.Column('visa_duration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_visa_id'], ['country_visas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visa_duration_id'], ['visa_durations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_visa_id', 'visa_duration_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_visa_duration')
    # ### end Alembic commands ###
