"""Set user role nullable = False

Revision ID: fe32b17c7e29
Revises: ff398cf0160f
Create Date: 2025-08-18 12:12:45.869397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'fe32b17c7e29'
down_revision = 'ff398cf0160f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'individual'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###
