"""Add role column to users table

Revision ID: ff398cf0160f
Revises: a4a7cb899ba5
Create Date: 2025-08-18 11:48:52.906572

"""
from alembic import op
import sqlalchemy as sa

from app.database.custom_types import ChoiceType
from app.models.users import User


# revision identifiers, used by Alembic
revision = 'ff398cf0160f'
down_revision = 'a4a7cb899ba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', ChoiceType(User.ROLE_CHOICES), server_default='individual', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
