"""Create clients table

Revision ID: ffd31ec8eaa5
Revises: d929fd812882
Create Date: 2025-08-21 11:48:14.263929

"""
from alembic import op
import sqlalchemy as sa

from app.database.custom_types import ChoiceType
from app.models.clients import Client

# revision identifiers, used by Alembic
revision = 'ffd31ec8eaa5'
down_revision = 'd929fd812882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', ChoiceType(Client.TYPE_CHOICES), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name='clients_tariff_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_tariff_id_fkey', 'clients', type_='foreignkey')
    op.drop_table('clients')
    # ### end Alembic commands ###
