name: App CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: python:3.12-slim
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.12]
      steps:
        - uses: actions/checkout@v4
        - name: Build Docker Image
          run: docker build . 