name: App CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        working-directory: backend
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        working-directory: backend
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          docker compose up -d
          docker exec visa_document_service-app-1 pytest
